Unify checks for normal
- Split up checks into multiple macros
- Use them in meta and impl functions for now since either might be called
- Get rid of what appear to be just legacy checks that are irrelevant now
- Update docs to not mention deprecated behavior.

Backward compatibility issues:

- Shapes must match exactly between mean and std (no automatic resizing):

Old:

>>> import torch
>>>
>>> mean = torch.rand(3, 4, 5, device='cpu')
>>> std  = torch.rand(3, 4, 1, device='cpu')
>>>
>>> torch.normal(mean=mean, std=std).size()
torch.Size([3, 4, 5])

New:

>>> import torch
>>>
>>> mean = torch.rand(3, 4, 5, device='cpu')
>>> std  = torch.rand(3, 4, 1, device='cpu')
>>>
>>> torch.normal(mean=mean, std=std)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: inconsistent tensor, output size ([3, 4, 5]) is not the same as
input size ([3, 4, 1])

- Tensors with the same number of elements are treated as different if their
  shapes don't match exactly:

Old:

>>> import torch
>>>
>>> out  = torch.rand(2, 3, device='cpu')
>>> mean = torch.rand(2, 3, device='cpu')
>>> std  = torch.rand(1, 6, device='cpu')
>>>
>>> torch.normal(out=out, mean=mean, std=std)
<stdin>:1: UserWarning: std and mean have the same number of elements, but are
not broadcastable. This was previously a supported mode of operation, but is
now deprecated and the support will be removed in version 1.6 release. Note
that the current implementation reshapes std to the shape of mean, which may be
incur data copies. Please ensure that std and mean are broadcastable to avoid
these issues. (Triggered internally at
aten/src/ATen/native/DistributionTemplates.h:189.)
tensor([[ 0.3345,  0.6314,  1.0163],
        [-0.0397,  0.8128,  1.1436]])

New:

>>> import torch
>>>
>>> out  = torch.rand(2, 3, device='cpu')
>>> mean = torch.rand(2, 3, device='cpu')
>>> std  = torch.rand(1, 6, device='cpu')
>>>
>>> torch.normal(out=out, mean=mean, std=std)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at
non-singleton dimension 1

- An empty tensor is returned instead of an error when mean is a float and std
  is an empty tensor:

Old:

>>> import torch
>>>
>>> mean = 4.
>>> std  = torch.rand(0, device='cpu')
>>>
>>> torch.normal(mean=mean, std=std)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: min(): Expected reduction dim to be specified for input.numel()
== 0. Specify the reduction dim with the 'dim' argument.

New:

>>> import torch
>>>
>>> mean = 4.
>>> std  = torch.rand(0, device='cpu')
>>>
>>> torch.normal(mean=mean, std=std)
tensor([])

ghstack-source-id: 4adf34a85ca0411c5c3b4d1ea394832f1f649179
Pull Request resolved: https://github.com/pytorch/pytorch/pull/69629